templateVersion: 1.0.0
defaultVersion: latest
documentation: https://docs.gitea.io
type: gitea
name: Gitea
description: Gitea is a community managed lightweight code hosting solution written in Go.
labels:
    - storage
    - git
services:
    $$id:
    	name: Gitea
        documentation: https://docs.gitea.io
        image: gitea/gitea:latest
        volumes:
            - $$id-data-git:/data/git
            - $$id-data-gitea:/data/gitea
        environment:
            - USER_UID=1000
            - USER_GID=1000
        ports:
            - '3000'
            - '22'
