templateVersion: 1.0.0
defaultVersion: RELEASE.2022-10-15T19-57-03Z
type: minio
name: MinIO
description: ' MinIO is a cloud storage server compatible with Amazon S3'
services:
  $$id:
    name: MinIO
    command: server /data --console-address :9001
    documentation: Taken from https://docs.min.io/docs/minio-docker-quickstart-guide.html
    depends_on: []
    image: minio/minio:$$core_version
    volumes:
      - $$id-data-write:/files
    environment:
      - MINIO_SERVER_URL=$$config_coolify_fqdn_minio_console
      - MINIO_BROWSER_REDIRECT_URL=$$config_minio_browser_redirect_url
      - MINIO_DOMAIN=$$config_minio_domain
      - MINIO_ROOT_USER=$$config_minio_root_user
      - MINIO_ROOT_PASSWORD=$$secret_minio_root_password
    ports:
      - '9000'
      - '9001'
    proxy:
      - port: '9000'
        domain: $$config_coolify_fqdn_minio_console
      - port: '9001'
variables:
  - id: $$config_coolify_fqdn_minio_console
    name: MINIO_SERVER_URL
    label: MinIO Server URL
    defaultValue: ''
    description: >-
      Specify the URL hostname the MinIO Console should use for connecting to
      the MinIO Server.
    required: true
  - id: $$config_minio_browser_redirect_url
    name: MINIO_BROWSER_REDIRECT_URL
    label: Browser Redirect URL
    defaultValue: $$generate_fqdn
    description: ''
  - id: $$config_minio_domain
    name: MINIO_DOMAIN
    label: Domain
    defaultValue: $$generate_domain
    description: ''
  - id: $$config_minio_root_user
    name: MINIO_ROOT_USER
    label: Root User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_minio_root_password
    name: MINIO_ROOT_PASSWORD
    label: Root User Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
