templateVersion: 1.0.0
defaultVersion: latest
documentation: https://docs.weblate.org/en/latest/admin/install/docker.html
type: weblate
name: Weblate
description: ''
services:
  $$id:
    name: Weblate
    depends_on:
      - $$id-postgresql
      - $$id-redis
    image: weblate/weblate:$$core_version
    volumes:
      - $$id-data:/app/data
    environment:
      - WEBLATE_SITE_DOMAIN=$$config_weblate_site_domain
      - WEBLATE_ADMIN_PASSWORD=$$secret_weblate_admin_password
      - POSTGRES_PASSWORD=$$secret_postgres_password
      - POSTGRES_USER=$$config_postgres_user
      - POSTGRES_DATABASE=$$config_postgres_db
      - POSTGRES_HOST=$$id-postgresql
      - POSTGRES_PORT=5432
      - REDIS_HOST=$$id-redis
    ports:
      - '8080'
  $$id-postgresql:
    name: PostgreSQL
    depends_on: []
    image: postgres:14-alpine
    volumes:
      - $$id-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$$config_postgres_user
      - POSTGRES_PASSWORD=$$secret_postgres_password
      - POSTGRES_DB=$$config_postgres_db
    ports: []
  $$id-redis:
    name: Redis
    depends_on: []
    image: redis:7-alpine
    volumes:
      - $$id-redis-data:/data
    environment: []
    ports: []
variables:
  - id: $$config_weblate_site_domain
    name: WEBLATE_SITE_DOMAIN
    label: Weblate Domain
    defaultValue: $$generate_domain
    description: ''
  - id: $$secret_weblate_admin_password
    name: WEBLATE_ADMIN_PASSWORD
    label: Weblate Admin Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
  - id: $$config_postgres_user
    main: $$id-postgresql
    name: POSTGRES_USER
    label: PostgreSQL User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_postgres_password
    main: $$id-postgresql
    name: POSTGRES_PASSWORD
    label: PostgreSQL Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
  - id: $$config_postgres_db
    main: $$id-postgresql
    name: POSTGRES_DB
    label: PostgreSQL Database
    defaultValue: weblate
    description: ''
